### ISSUE TITLE
This template doesn't work properly with CoffeScript 1.7+

### ISSUE THREAD

**Issue by rcrichton** [twilson63/cakefile-template#13]
To support CoffeeScript 1.7+ apparently the args passed to Mocha need to be changed. The args should now be: --compilers coffee:coffee-script/register

I'm not sure how you want to handle this. Keep this repo supporting 1.6, migrate to 1.7+ or try support both.

Reference: http://stackoverflow.com/questions/9940838/cannot-run-mocha-with-coffeescript

**Comment by blahah** [comment]
Fixed in https://github.com/twilson63/cakefile-template/pull/16
